services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=finance_tracker'
      - 'POSTGRES_PASSWORD=finance_pass'
      - 'POSTGRES_USER=finance_user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'